version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: lynx-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lynx-admin
      POSTGRES_PASSWORD: auT*k!K9Tp(8
    volumes:
      - lynx-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  lynx-db-data: